using UnityEngine;
using UnityEngine.Events;
using System.Collections;

namespace MinVR
{
	public class VRButtonListener : MonoBehaviour
	{
		[Tooltip ("The name of the VREvent generated by the button tracker (e.g., Brush0_Top_Button, Brush0_Bottom_Button).")]
		public string buttonEventName = "";
		[Tooltip ("The name of the VRDataIndex field where the button state data is stored , typically action.")]
		public string buttonStateField = "";
		[Tooltip ("The events that are executed for a button-down event.")]
		public UnityEvent buttonDownEvent;
		[Tooltip ("The events that are executed for a button-up event.")]
		public UnityEvent buttonUpEvent;

		void Start ()
		{
			VRMain.VREventHandler += OnVREvent;
		}

		void OnVREvent (VREvent e)
		{
			if (e.Name == buttonEventName) {
				// (0 or 1) that usually means (released or pressed)
				int state = e.DataIndex.GetValueAsInt (buttonStateField);
				//Debug.Log("Event name = " + e.Name);
				//Debug.Log("Button state = " + state);

				if (state == 1) {
					buttonDownEvent.Invoke ();
				} else if (state == 0) {
					buttonUpEvent.Invoke ();
				}
			}
		}
	}
}
// namespace MinVR